### ISSUE TITLE
刚打开窗口的时候选筛选必crash

### ISSUE THREAD

**Issue by JenningsWu** [poooi/plugin-item-info#18]
![78 iqzmya2hd ry uid y0](https://cloud.githubusercontent.com/assets/6861365/11469791/d6cca1de-970d-11e5-8ae8-e2c2329b315b.png)
![l eae b y s35dbmo ed1w](https://cloud.githubusercontent.com/assets/6861365/11469794/dc1daa3e-970d-11e5-8bab-7007e557e348.png)
大概是和加载 devTool 有关，还没完全打开就选筛选的话就会崩。经常手快导致这个。。略蛋疼。
嗯，说不定也是 win 特有 bug？

**Comment by taroxd** [comment]
也许是我手速不够，无法重现。

我这里是 electron 0.35.2

**Comment by JenningsWu** [comment]
可能和特定的 electron 版本有关。最开始报告这个问题的时候情况是第一次打开的时候有很长一段时间（体感有3~5秒）鼠标移到筛选框上时不会变成手型，而在这个时候如果点了筛选框就一定会崩。几秒后鼠标能变成手型时再点击就不会崩。
现在又试了下，发现已经没有这个问题了。electron 0.36.1
