### ISSUE TITLE
[Feature Request] 增加舰载机熟练度显示

### ISSUE THREAD

**Issue by wafer-li** [poooi/plugin-item-info#2]
RT
可以将舰载机熟练度视为改修星数来进行同装备不同熟练度的显示

**Comment by hanzhao** [comment]
master里有啊

**Comment by wafer-li** [comment]
@magicae 
![qq 20150814221745](https://cloud.githubusercontent.com/assets/12459199/9274623/56cefd86-42d2-11e5-9835-1751e4545ee2.png)

然而这个插件面板里面并没有
顺便给一个`log`
![qq 20150814221857](https://cloud.githubusercontent.com/assets/12459199/9274662/8fc1c04c-42d2-11e5-8d2b-57881e9dedfb.png)

**Comment by hanzhao** [comment]
哦我看错repo了

**Comment by hanzhao** [comment]
Fixed by https://github.com/poooi/plugin-item-info/pull/5 .
