### ISSUE TITLE
装备顺序与废弃装备页面顺序不一致

### ISSUE THREAD

**Issue by yukixz** [poooi/plugin-item-info#25]
咩~

**Comment by taroxd** [comment]
萌新求教，废弃装备页面是啥顺序

理论上只要把 sort 函数的参数改一下就好了

**Comment by yukixz** [comment]
不知道=_=
今天边看装备数量边拆就发现不一样了（

On Wednesday, 6 April 2016, taroxd notifications@github.com wrote:

> 萌新求教，废弃装备页面是啥顺序
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/poooi/plugin-item-info/issues/25#issuecomment-206375793

## 

_Dazzy Ding_
Email: h@dazzyd.org

**Comment by yukixz** [comment]
游戏里装备排序应该用的是 `api_type[2]` 作为排序规则
~~但是这样 51大根这些装备就会跑到最后面去~~
重新看了下 api_start2、特殊装备的 id 改成跟普通装备用的同个 id 了？

On Wed, Apr 6, 2016 at 9:36 PM, Dazzy Ding h@dazzyd.org wrote:

> 不知道=_=
> 今天边看装备数量边拆就发现不一样了（
> 
> On Wednesday, 6 April 2016, taroxd notifications@github.com wrote:
> 
> > 萌新求教，废弃装备页面是啥顺序
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/poooi/plugin-item-info/issues/25#issuecomment-206375793
> 
> ## 
> 
> _Dazzy Ding_
> Email: h@dazzyd.org

## 

_Dazzy Ding_
Email: h@dazzyd.org

**Comment by yukixz** [comment]
bump、试了下改 sort
排序规则应该是 
1. api_type[2]
2. api_slotitem_id
