### ISSUE TITLE
Support "airplane is equipped at base airport"

### ISSUE THREAD

**Issue by dkwingsmt** [poooi/plugin-item-info#28]
添加“该装备在陆航装备中”的支持。

今天我找半天发现找不到我的岩本队了，任何舰娘上都没有。吓死我了。后来经人提醒才想起来在陆航上。
![image](https://cloud.githubusercontent.com/assets/1596656/15587257/feab426a-234d-11e6-9df5-4fd419aac278.png)

**Comment by taroxd** [comment]
本来准备做的，结果没找到API= =

怀疑娇喘根本没告诉你飞机是否装备在航空队上，只通过 unsetslot 告诉你可用的装备有哪些

I was to implement it but tanaka's mother boomed.

**Comment by dkwingsmt** [comment]
直接把没有 unsetslot 的全部标记为航空队呗？

**Comment by taroxd** [comment]
我可以试试把 unsetslot 中数据与计算得出的数据不符时高亮那一行，但不敢标注陆航。

**Comment by dkwingsmt** [comment]
暂时也没有别的可能性吧？

**Comment by dkwingsmt** [comment]
陆航的飞机只有在点击活动地图的时候才会获取
