### ISSUE TITLE
[Feature request]增加搜索功能

### ISSUE THREAD

**Issue by terencefan** [poooi/plugin-item-info#3]
如输入20.3，出来1号2号3号炮的信息

此外，顶上的筛选希望能做成点击筛选的方式，现在每次的操作都是
取消全选－选择某类 
希望能简化掉第一步的操作

**Comment by taroxd** [comment]
搜索功能已完成，会在 4.2.0 版本中发布

如果按照你的要求简化筛选的话，就没法支持多选功能了。
