### ISSUE TITLE
左键点击失效

### ISSUE THREAD

**Issue by wafer-li** [poooi/plugin-item-info#31]
左键点击某个装备门类复选框时无反应。

估计是因为本体升级 React 引起的？

**Comment by KochiyaOcean** [comment]
React-Bootstrap 的问题。这个版本实在太糟糕了……本体已经退回

**Comment by wafer-li** [comment]
@KochiyaOcean 
嗯…… 所以是更新本体咯？

顺便问一下有升级 electron 的计划吗？

**Comment by taroxd** [comment]
>= 0.37.0, <= 1.1.3 有触屏 bug
1.2.0……还是等等zc菊苣吧

如果你不用触屏，而且用的是开发版（目测就是这样了），你可以手工把 electron 升级到 1.1.3
